### PR TITLE
cleanup build

### PR DESCRIPTION
**Pull request by danrubel**
@devoncarew

### CODE REVIEW

**Comment by danrubel** [comment]
Signal dartlang to enable Dartino specific features

@devoncarew

**Comment by danrubel** [comment]
Fixes https://github.com/dartino/atom-dartino/issues/37

**Comment by devoncarew** [comment]
lgtm

**Comment by danrubel** [comment]
Merged https://github.com/dartino/atom-dartino/commit/e12913945913fc038ee3bf85801fe99f0ca0dfcd

**Pull request closed without merging**
